<script setup>
import { Head } from '@inertiajs/vue3';
import PublicLayout from '../Layouts/PublicLayout.vue';
const stories = [
  { section: 'BAGIAN 1', title: 'Awal Mula & Visi Sederhana', image: '/assets/temporary/about-foundation.png', paragraphs: ['Didirikan dengan semangat untuk menyediakan ruang rekreasi keluarga terpadu di Jambi, Kampoeng Radja bermula dari sebuah visi sederhana: menciptakan tempat dimana tawa anak-anak bergema melampaui hiruk pikuk kota.', 'Sebuah mimpi untuk memberikan sarana liburan yang terjangkau namun berkesan bagi masyarakat lokal menjadi dorongan utama untuk mewujudkan proyek ambisius ini.'] },
  { section: 'BAGIAN 2', title: 'Transformasi & Komitmen', image: '/assets/temporary/about-hero-aerial.png', paragraphs: ['Sejak peletakan batu pertama, kami berkomitmen memadukan unsur hiburan modern dengan nilai-nilai kekeluargaan lokal. Melalui dedikasi yang tak kenal lelah, sebagian tanah luas perlahan bertransformasi menjadi oase kegembiraan.', 'Setiap pengembangan didasarkan pada riset yang mendalam dan umpan balik berharga dari para pengunjung.'] },
  { section: 'BAGIAN 3', title: 'Menjadi Destinasi Professional Joy', image: '/assets/temporary/about-opening.png', paragraphs: ['Hari ini, Kampoeng Radja berdiri tidak hanya sebagai taman hiburan, melainkan sebagai institusi Professional Joy — di mana setiap proses dikelola dengan ketelitian korporat demi memastikan pengalaman bermain yang aman, bersih, dan berkesan bagi setiap pengunjung.', 'Tim ahli kami bekerja siang dan malam untuk menjaga standar operasional yang tinggi, agar setiap kunjungan menjadi momen istimewa yang akan dikenang sepanjang masa.'] },
];
</script>
<template><Head title="Tentang Kami"><meta name="description" content="[PLACEHOLDER: Deskripsi Tentang Kami]" /></Head><PublicLayout>
  <section class="relative grid h-[640px] place-items-center overflow-hidden bg-[#173e59] text-center text-white"><img src="/assets/temporary/about-hero-aerial.png" alt="[FIGMA SEMENTARA] Tampak aerial Kampoeng Radja" class="absolute inset-0 h-full w-full object-cover" /><div class="absolute inset-0 bg-[#002147]/50"></div><div class="relative"><h1 class="font-heading text-4xl font-extrabold lg:text-[48px]">Kampoeng Radja</h1><p class="mt-5 text-xl font-bold text-white/90">"Kesenangan Tiada Akhir di Kampoeng Radja"</p></div></section>
  <section class="bg-white px-5 py-20 lg:px-0"><div class="mx-auto max-w-[1120px] space-y-12"><article v-for="(story,index) in stories" :key="story.section" :class="index % 2 ? 'lg:flex-row-reverse' : ''" class="flex flex-col items-center gap-8 lg:flex-row"><div class="flex-1"><span class="rounded-full bg-[#fce7f3] px-3 py-1 font-mono text-[10px] font-semibold tracking-[.15em] text-[#be185d]">{{ story.section }}</span><h2 class="mt-4 font-heading text-2xl font-bold text-[#191c1e]">{{ story.title }}</h2><div class="mt-3 h-[3px] w-10 rounded-full bg-[#0063c7]"></div><p v-for="paragraph in story.paragraphs" :key="paragraph" class="mt-5 text-sm leading-5 text-[#434655]">[FIGMA SEMENTARA] {{ paragraph }}</p></div><img :src="story.image" :alt="`[FIGMA SEMENTARA] ${story.title}`" class="h-[255px] w-full flex-1 rounded-xl object-cover shadow-sm" /></article></div></section>
  <section class="bg-white px-5 py-20 lg:px-0"><div class="mx-auto max-w-[1120px]"><div class="text-center"><span class="rounded-full bg-[#fce7f3] px-3 py-1 font-mono text-[10px] font-semibold tracking-[.15em] text-[#be185d]">LANDASAN KAMI</span><h2 class="mt-4 font-heading text-2xl font-bold text-[#191c1e]">Visi & Misi</h2></div><div class="mx-auto mt-7 grid max-w-[864px] gap-4 md:grid-cols-2"><article class="min-h-[250px] rounded-2xl border border-[#dbe7ff] bg-[linear-gradient(135deg,#fff,#f7f9ff)] p-5"><span class="grid h-8 w-8 place-items-center rounded-lg bg-[#d7e2ff] text-[#0052c8]">◉</span><h3 class="mt-4 font-heading text-base">Visi</h3><p class="mt-3 text-[13px] leading-5 text-[#434655]">[FIGMA SEMENTARA] Menjadi destinasi rekreasi keluarga terdepan dan paling terpercaya di Sumatera, yang memadukan hiburan inovatif dengan standar pelayanan profesional untuk menciptakan kebahagiaan sejati.</p></article><article class="min-h-[250px] rounded-2xl border border-[#f5e3d7] bg-[linear-gradient(135deg,#fff,#fdf9f6)] p-5"><span class="grid h-8 w-8 place-items-center rounded-lg bg-[#ffdcc3] text-[#9d4300]">◎</span><h3 class="mt-4 font-heading text-base">Misi</h3><ul class="mt-3 grid gap-2 text-[12px] leading-4 text-[#434655]"><li v-for="item in ['Menyediakan wahana rekreasi yang aman, bersih, dan berstandar internasional.', 'Menerapkan manajemen operasional yang efisien berbasis pada prinsip Professional Joy.', 'Mengembangkan sumber daya manusia yang ramah, tanggap, dan berdedikasi tinggi.', 'Berkontribusi positif terhadap lingkungan dan masyarakat sekitar Jambi.']" :key="item" class="flex gap-3"><span class="text-[#9d4300]">⊙</span><span>[FIGMA SEMENTARA] {{ item }}</span></li></ul></article></div></div></section>
  <section class="bg-[#f7f9fb] px-5 py-20 lg:px-0"><div class="mx-auto max-w-[1120px] text-center"><h2 class="font-heading text-2xl font-bold">Struktur Organisasi</h2><p class="mt-4 text-[#434655]">[PERLU KONTEN RESMI: Struktur organisasi publik.]</p><div class="mt-10 flex flex-col items-center gap-6"><div class="rounded-xl bg-[#1e3a8a] px-8 py-5 text-white">[PERLU DATA: Komisaris]</div><div class="rounded-xl bg-[#004ac6] px-8 py-4 text-white">[PERLU DATA: Direksi]</div><div class="grid gap-5 md:grid-cols-2"><div class="rounded-lg border bg-white px-8 py-5">[PERLU DATA: SPV Marcom]</div><div class="rounded-lg border bg-white px-8 py-5">[PERLU DATA: SPV Operasional]</div></div></div></div></section>
</PublicLayout></template>
